/* ORIGINAL DATABASE ALL WHOLE LOT EXECUTES TOGETHER......................................*/

DROP TABLE ORDERITEM;
DROP TABLE PRODUCT;
DROP TABLE THEORDER;
DROP TABLE CUSTOMER;
DROP TABLE SUPPLIER;
DROP TABLE THEUSER;



CREATE TABLE CUSTOMER(
    CUSTOMERID 		  NUMBER(11) NOT NULL,
    FIRSTNAME 		  VARCHAR(50) NOT NULL,
    LASTNAME 		  VARCHAR(50) NOT NULL,
    ADDRESS1 	  	  VARCHAR(50) NOT NULL,
	ADDRESS2 		  VARCHAR(50) NOT NULL,
	CITY 		  	  VARCHAR(20) NOT NULL,
	COUNTY 		  	  VARCHAR(20) NOT NULL,
	COUNTRY 		  VARCHAR(20) NOT NULL,
	ZIP 		  	  VARCHAR(20) NOT NULL,
	PHONE 		  	  VARCHAR(20) NOT NULL,
	CARDTYPE 		  VARCHAR(20) NOT NULL,
	CARDNUMBER 		  VARCHAR(20) NOT NULL,
	CARDIDNUMBER 	  VARCHAR(20) NOT NULL,
	VALIDUNTIL 		  VARCHAR(20) NOT NULL,
	CONSTRAINT pk_custid PRIMARY KEY (CUSTOMERID)
);

							 
CREATE TABLE THEORDER (
    ORDERID 					NUMBER(11) NOT NULL,
    CUSTOMERID 					NUMBER NOT NULL,
    ORDERDATE  				    date,
    CONSTRAINT pk_orderid PRIMARY KEY (ORDERID),
    CONSTRAINT fk_custid FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER (CUSTOMERID)
);	


CREATE TABLE SUPPLIER(
    SUPPLIERID 				INTEGER(11) NOT NULL AUTO_INCREMENT,
    SUPPLIER_NAME			VARCHAR(40) NOT NULL,
	SUPPLIER_ADDRESS 		VARCHAR(30) NOT NULL,
	SUPPLIER_TELNO 		    VARCHAR(20) NOT NULL,
	CONSTRAINT pk_supplierid PRIMARY KEY (SUPPLIERID)
);

						 
CREATE TABLE PRODUCT(
    PRODUCTID 				NUMBER(11) NOT NULL,
	SUPPLIERID 				NUMBER NOT NULL,
	ALBUM_COVER				VARCHAR(100)NOT NULL,
	PRODUCTCODE				VARCHAR(30)NOT NULL,
    PRODUCT_NAME			VARCHAR(30)NOT NULL,
    PRODUCT_GENRE			VARCHAR(30)NOT NULL,
    PRODUCT_DESC 			VARCHAR(5000) NOT NULL,
    PRODUCT_PRICE 			DOUBLE(7,2) NOT NULL,
    CONSTRAINT pk_productid PRIMARY KEY (PRODUCTID),
	CONSTRAINT fk_supplierid FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER (SUPPLIERID)
);


CREATE TABLE ORDERITEM(
    ORDERID 		NUMBER NOT NULL,
    PRODUCTID 		NUMBER NOT NULL,
    CONSTRAINT pk_orderitemid PRIMARY KEY (ORDERID, PRODUCTID),
    CONSTRAINT fk_orderid FOREIGN KEY (ORDERID) REFERENCES THEORDER (ORDERID),
	CONSTRAINT fk_productid FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT (PRODUCTID)
);

CREATE TABLE THEUSER (
    USERID 		  	  NUMBER(11) NOT NULL,
    FIRSTNAME 		  VARCHAR(50) NOT NULL,
    LASTNAME 		  VARCHAR(50) NOT NULL,
    EMAILADDRESS 	  VARCHAR(50) NOT NULL,
	USERNAME 		  VARCHAR(50) NOT NULL,
	PASSWORD 		  VARCHAR(50) NOT NULL,
	CONSTRAINT pk_userid PRIMARY KEY (USERID)
);
