/* ORIGINAL DATABASE ALL WHOLE LOT EXECUTES TOGETHER......................................*/

DROP TABLE ORDER_ITEM;
DROP TABLE PRODUCT;
DROP TABLE LOCAL_ORDER;
DROP TABLE CUSTOMER;
DROP TABLE SUPPLIER;
DROP TABLE SELLER;
DROP TABLE ADDRESS;

