/* ORIGINAL DATABASE ALL WHOLE LOT EXECUTES TOGETHER......................................*/

DROP TABLE ORDERITEM;
DROP TABLE PRODUCT;
DROP TABLE THEORDER;
DROP TABLE CUSTOMER;
DROP TABLE SUPPLIER;
DROP TABLE THEUSER;

